== Demo 1 - JBoss Fuse 6.3 with Camel CBR

* Open IntelliJ and move to the quickstarts folder `/Users/chmoulli/Fuse/Fuse-servers/jboss-fuse-6.3.0.redhat-187/quickstarts`

* Open a terminal for `beginner/camel-cbr`

* Compile the project `mvn clean install`

* Start JBoss Fuse 6.3

* Deploy the bundle `osgi:install -s mvn:org.jboss.quickstarts.fuse/beginner-camel-cbr/6.3.0.redhat-187`

* Open the web console and show the camel route

* Copy some files

```
export DEST=/Users/chmoulli/Fuse/Fuse-servers/jboss-fuse-6.3.0.redhat-187/work/cbr/input/
cp src/main/fabric8/data/order1.xml $DEST
cp src/main/fabric8/data/order2.xml $DEST
cp src/main/fabric8/data/order3.xml $DEST
cp src/main/fabric8/data/order4.xml $DEST
```

* Enable the tracing & copy a file

```
cp src/main/fabric8/data/order5.xml $DEST
```

Verify within the console that you can see the detail about the message and where it fits

== DEMO 2 - JBoss Fuse 6.3 - Fabric8 & Apache CXF Rest Endpoint

* Create Fabric Ensemble (wifi connection is required)

```
cd /Users/chmoulli/Fuse/Fuse-servers/jboss-fuse-6.3.0.redhat-187/bin
rm -rf ../data
rm -rf ../instances
./fuse

fabric:create
```

* Open IntelliJ and move to the quickstarts folder `/Users/chmoulli/Fuse/Fuse-servers/jboss-fuse-6.3.0.redhat-187/quickstarts`

* Open a terminal for `cxf/rest`

* Run `mvn compile fabric8:deploy` to create the profile

* Create a child container `cxf-rest` and assign the profile

* Visit the APi view & select swagger to display the REST endpoint doc

* Issue some REST requests

* To get customer

Remark : change the port number

```
    http GET http://localhost:8080/cxf/rest/customerservice/customers/123
    http GET http://localhost:8080/cxf/rest/customerservice/customers/124
```

* To Post
```
    echo '{"Customer":{"name":"TUG"}}' | http POST http://localhost:8080/cxf/rest/customerservice/customers
```
* To Update
```
    echo '{"Customer":{"id":124,"name":"TUG2"}}' | http PUT http://localhost:8080/cxf/rest/customerservice/customers
```
* To delete
```
    http DELETE http://localhost:8080/cxf/rest/customerservice/customers/124
```

* Issue some REST requests

```
    http GET http://localhost:8182/cxf/rest/customerservice/customers/123
    http GET http://localhost:8182/cxf/rest/customerservice/customers/124
    echo '{"Customer":{"name":"TUG"}}' | http POST http://localhost:8182/cxf/rest/customerservice/customers
    echo '{"Customer":{"id":124,"name":"TUG2"}}' | http PUT http://localhost:8182/cxf/rest/customerservice/customers
    http DELETE http://localhost:8182/cxf/rest/customerservice/customers/124
```

* Stop the container
```
    fabric:container-stop cxf-rest
```

== DEMO 3 - OpenShift with a SpringBoot Camel Service

* Start Minishift & install the Fabric8 Web Console
```
minishift delete
minishift start --memory 6000 --deploy-router
gofabric8 deploy --app=console
```
* Authenticate the user with the OpenShift platform
```
oc login -u admin -p admin
```

* Move to the Camel Demo project
```
cd ~/Fuse/projects/fabric8/quickstarts/spring-boot-camel
```

* Build the project and deploy it on Openshift
```
mvn clean compile fabric8:run
```

* Open the OpenShift web console

- Show the pod created, service & the log
- Access the jolokia Web Console to show the camel route

== DEMO 3 - OpenShift with 2 Camel Microservices

* Open the projects containing the MicroServices
```
cd /Users/chmoulli/MyProjects/microservice
```

* Install the MySQL Template & image
```
eval $(minishift docker-env)
oc create -f https://raw.githubusercontent.com/openshift/origin/master/examples/db-templates/mysql-ephemeral-template.json
docker pull openshift/mysql-56-centos7
```
* Create the DB
```
oc new-app -e \
    MYSQL_USER=admin,MYSQL_PASSWORD=admin,MYSQL_DATABASE=sampledb \
    openshift/mysql-56-centos7
```

* Change the name of service within the deployment cfg file as the service created is not longer mysql
```
env:
- name: MYSQL_SERVICE_NAME
  value: mysql-56-centos7
```

* Deploy the SpringBoot Camel REST & SQL demo
```
mvn fabric8:deploy -Dmysql-service-username=admin -Dmysql-service-password=admin -Dmysql-service-name=mysql-56-centos7
```

* Check the pod, service & log
* Access the Hawtio Web Console
* Call the REST endpoint
```
http $(minishift service spring-boot-camel-rest-s --url=true)/camel-rest-sql/books
```
* Use Swagger UI

- To get the IP address of the Endpoint/Service
http $(minishift service spring-boot-camel-rest-s --url=true)/camel-rest-sql/api-doc

- Next, open your browser at this address to fetch the endpoint info using the Swagger UI

chrome http://$(minishift ip):8888/swagger-ui/?url=$(minishift service spring-boot-camel-rest-s --url=true)/camel-rest-sql/api-doc







